apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-docker-integration-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jenkins-docker-integration
  template:
    metadata:
      labels:
        app: jenkins-docker-integration
    spec:
      containers:
      - name: jenkins-docker-integration
        image: modepallivenki/jenkins-docker-integration
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-docker-integration-service
spec:
  selector:
      app: jenkins-docker-integration
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort
